////
SPDX-License-Identifier: CC-BY-4.0
////

= Toolchains SIG
:uri-license: {uri-rel-file-base}LICENSE

This is the home of the RISC-V Toolchains SIG
The SIG's charter can be found link:./charter.adoc[here].

* Chair: Christoph Müllner
* Co-Chair: Evandro Menezes

We are reporting to the Applications & Tools HC.

== Regular meetings

The Toolchains SIG meets bi-weekly.
For more info see link:./meetings/README.adoc[here].

== Toolchain and Runtimes monitored projects

The Toolchains SIG is monitoring the RISC-V status of a range of external projects.
For more info see link:https://wiki.riscv.org/display/TECH/RISC-V+Software+Ecosystem[here].

== CI service for GNU toolchain

A CI service for several RISC-V GNU toolchain flavours can be found
link:https://ci.rvperf.org/view/GNU/[here].

This service is maintained by Wei Wu (PLCT).
Suggestions are discussed link:https://github.com/riscv/riscv-gnu-toolchain/issues/847[here].

= Links

* link:https://wiki.riscv.org/display/TECH/Tech+Home[RVI Tech Home]
* link:https://github.com/riscv/riscv-elf-psabi-doc[psABI documentation]
* link:https://github.com/riscv/riscv-platform-specs[RISC-V Platform Specification]
* link:https://github.com/riscv/riscv-code-size-reduction[SIG Code Size GitHub page]
* link:https://github.com/riscv/riscv-software-list[RISC-V Software List]
* link:https://godbolt.org[Compiler explorer]
