////
SPDX-License-Identifier: CC-BY-4.0
////

= Toolchains and Runtimes HSC
:uri-license: {uri-rel-file-base}LICENSE

This is the home of the RISC-V Toolchains and Runtimes HSC.
The HSC's charter can be found link:./charter.adoc[here].

* Chair: Christoph Müllner
* Co-Chair: Evandro Menezes

We are reporting to the RVI Software HC.

Our reporting RVI groups:

* TG Overlays
* SIG Code Speed
* TG psABI (in inception phase)
* TG EABI
* SIG Managed Runtimes (in inception phase)

Planned future groups:

* SIG DB/App
* SIG AI/ML/NLP
* SIG HPC

== Regular meetings

The Toolchain and Runtimes HSC meets bi-weekly.
For more info see link:./meetings/README.adoc[here].

== Toolchain and Runtimes related information

An overview of the release dates of upstream projects
related to our work can be found link:./releasedates.adoc[here].

The current status of RV extension support can be found
link:./extension-support.adoc[here].

LLVM holds biweekly sync-up link:https://lists.llvm.org/pipermail/llvm-dev/2019-September/135087.html[calls].
Next link:https://lists.llvm.org/pipermail/llvm-dev/2021-February/148345.html[call] is scheduled for 18th Feb 2021.

= Links

* link:https://wiki.riscv.org/display/TECH/Tech+Home[RVI Tech Home]
* link:https://github.com/riscv/riscv-elf-psabi-doc[psABI documentation]
* link:https://github.com/riscv/riscv-platform-specs[RISC-V Platform Specification]
* link:https://github.com/riscv/riscv-code-size-reduction[SIG Code Size GitHub page]
* link:https://github.com/riscv/riscv-software-list[RISC-V Software List]
* link:https://godbolt.org[Compiler explorer]
