////
SPDX-License-Identifier: CC-BY-4.0
////

= Monitoring of upstream projects (language set)
:toc:

This page gives an overview of upstream projects.
If you miss information or find mistakes, please file a PR.

== GHC

The Glasgow Haskell Compiler (GHC) is an open-source
compiler for the programming language Haskell.

* https://www.haskell.org/ghc/[GHC homepage]

=== RISC-V status

GHC does not support RISC-V, but there are people working on it.
The porting attempts are tracked here:

* https://gitlab.haskell.org/ghc/ghc/-/issues/16783

== Go

Go is a programming language designed for simplicity,
reliability and efficiency.

* https://golang.org/[Go Homepage]

=== RISC-V status

RISC-V support has been mainlined with Go 1.14.

== OpenJDK

OpenJDK is an open-source implementation of the Java Platform (Java SE).

* https://openjdk.java.net/projects/jdk/[OpenJDK Homepage]
* https://github.com/openjdk/jdk[OpenJDK github repository]

=== RISC-V status

Two independent teams started working on the OpenJDK port.

The BishengJDK team is lead by Yadong Wang.
They have published the first HotSpot JIT port for RV64G.

The PLCT team is lead by Ningning Shi.

Both teams are collaborating and working on a common
link:https://github.com/openjdk-riscv/[RISC-V port].

The status of OpenJDK/HotSport RV64G JIT porting could be found
link:https://groups.google.com/a/groups.riscv.org/g/sw-dev/c/HziqjQ_2o2w[here].
They are very optimistic to reach their 100x speed up
link:https://groups.google.com/a/groups.riscv.org/g/sw-dev/c/fIYoDnpqww8[goal].

== PHP

PHP is a programming language targeting web development.

* https://www.php.net/[PHP homepage]

=== RISC-V status

The PHP interpreter works on RISC-V.
However, certain features, such as the PCRE JIT, are not ported yet
and there are no RISC-V specific optimization in the code base at the moment.
Thus optimal perfomance cannot be achieved right now.

== Rust

Rust is a programming language designed for performance,
reliability and productivity.
It relies on LLVM for generating code.

* https://www.rust-lang.org/[Rust Homepage]

=== RISC-V status

Rust has tier 2 support for RISC-V RV64 (riscv64gc-unknown-linux-gnu)
since 1.42.0 (2020-03-12).
RV32 is supported, but currenlty does not have a complete standard library.

* https://doc.rust-lang.org/nightly/rustc/platform-support.html

== V8

V8 is a JavaScript and WebAssembly engine with a strong
focus on performance.

V8 is used a JavaScript runtime for other runtimes/projects, such as

* Google Chrome Browser
* Chromium Browser
* Node.js

=== RISC-V status

PLCT is working on the link:https://github.com/v8-riscv/v8/[RISC-V port].
The team is lead by Peng Wu.
She and her team have managed to get their RV64GCV port
link:https://bugs.chromium.org/p/v8/issues/detail?id=10991#c23[mainline]
in February 2021.
The project's 2021 roadmap can be found
link:https://github.com/v8-riscv/v8/issues/366#issuecomment-756183363[here].

