////
SPDX-License-Identifier: CC-BY-4.0
////

= Toolchains and Runtimes HSC
:uri-license: {uri-rel-file-base}LICENSE

This page lists current identified gaps in the T&R ecosystem
as idenified by the RISC-V T&R group.

The gaps have the following properties:

* Title
* Tags
* Date
* Description
* Comparision to competition

The Tags help to structure the information.
Possible values are:

* psABI
* Compilers
* Runtimes
* Extension enablement
* Performance

== Gaps ==

=== Fine-grained cost model ===

* Tags: Compilers, Performance
* Date: 14.2.2022
* Description: The backend of GCC lacks a fine-grained cost model to optimize code generation for specific cores.
* Comparision to competion: Backends for other architectures (AArch64, PowerPC, x86-64) have that.

=== I-func support ===

* Tags: Runtimes, Performance
* Date: 14.2.2022
* Description: Glibc offers an indirection mechanism to call target-specific implementations for functions like strlen, strcmp, memcmp. Upstream glibc does not untilize this mechanism and uses therefore unoptimized implementations.
* Comparison to competition: All other competitors utilize glibc's i-func support.

=== Auto-vectorization ===

* Tags: Compilers, Performance
* Date: 14.2.2022
* Description: The (recently ratified) RISC-V vector extension allows to utilize and extend GCC's auto-vectorization capabilities. Currently, there is no (public information about) active work in this area.
* Comparison to competition: There has been quite some work on vectorization topics in the last 10 years in GCC. Initially much was focussed on x86. Recently AArch64 improved and extended the auto-vectorization capabilties of GCC with the integration of the SVE support.


